# Generated by Django 3.2.3 on 2021-06-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('genre', models.CharField(max_length=50, verbose_name='장르')),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='제목')),
                ('image', models.ImageField(upload_to='category/images', verbose_name='공연포스터')),
                ('date', models.DateField(auto_now=True, verbose_name='공연날짜')),
                ('location', models.CharField(max_length=128, verbose_name='공연장소')),
                ('member', models.CharField(max_length=128, verbose_name='출연진')),
                ('overview', models.TextField(max_length=500, verbose_name='공연개요')),
            ],
            options={
                'verbose_name': '공연',
                'verbose_name_plural': '공연',
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='PerformanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageGroup', models.CharField(max_length=20, verbose_name='관람 연령')),
                ('viewingTime', models.CharField(max_length=20, verbose_name='관람 시간')),
                ('priceVIP', models.CharField(max_length=20, verbose_name='VIP석')),
                ('priceR', models.CharField(max_length=20, verbose_name='R석')),
                ('priceS', models.CharField(max_length=20, verbose_name='S석')),
                ('info_time', models.CharField(max_length=128, verbose_name='시간 안내')),
                ('info_delivery', models.CharField(max_length=128, verbose_name='티켓 배송 안내')),
                ('title', models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, to='category.performance')),
            ],
            options={
                'verbose_name': '공연 상세',
                'verbose_name_plural': '공연 상세',
                'db_table': 'performance_detail',
            },
        ),
    ]
