# Generated by Django 3.2.3 on 2021-06-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('username', models.CharField(max_length=5, verbose_name='성명')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('telephone_number', models.CharField(max_length=128, verbose_name='전화번호')),
                ('resident_number', models.CharField(max_length=128, verbose_name='주민번호')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'users',
            },
        ),
    ]
